### ISSUE TITLE
Compilation 

### ISSUE THREAD

**Issue by hcmturner** [01org/edison-bcm43340#1]
Hi,

How can I compile this module so that it works correctly on an the Edison? 
What flags need to be used?

Just running make using the kernel headers compiles a module however this module gets a 'siocsifflags operation not permitted' when you run the wlan0 up command.

Thanks
Henry

**Comment by vinh869163** [comment]
do your module run? I can not compile. It always show "no directory"

**Comment by chenchux** [comment]
Please don't compile edison-bcm43340 alone, because it is only a layer, and it will be fetched and compiled automatically when you compiling Edison source code. 

Here is a steps  using for compiling Edison source code:

1- Prepare your workspace:
$ mkdir my_Edison_Workspace

2- Get this layer:
$ git clone git://git.yoctoproject.org/meta-intel-edison

3- Make things easier with 'make':
$ ln -s meta-intel-edison/utils/Makefile.mk Makefile

4- Download all the needed dependencies:
$ make setup

5- Build Intel Edison Yocto distribution:
$ make edison-image

6- Flash the board:
$ make flash

**Comment by vinh869163** [comment]
can this code work on computer x64

**Comment by vinh869163** [comment]
can this code work on ubuntu 14.04 64bit?

**Comment by chenchux** [comment]
This code is one part of Intel Edison source code, and it will be integrated in Yocto OS when compiling edison image. I don't tried on Ubuntu PC, so can not answer you question.

**Comment by andy-shev** [comment]
@vinh869163, @hcmturner 
Since upstream kernel (let's say v4.13 is a good start) more or less supports Edison  out-of-the-box, there is no need to use this repository at all.
